### ISSUE TITLE
requests for BM (black morass) show up in ramparts

### ISSUE THREAD

**Issue by prowley** [Vysci/LFG-Bulletin-Board#103]
Using default settings, I figured Id change the filter but it doesnt seem to save.

**Comment by thickey3** [comment]
I am also seeing this

**Comment by the-chuppa** [comment]
I think I figured out what's going on. There is a "BM" string in the german search pattern for Ramparts. Whether this is correct or not for german language I do not know. But the solution is to go to the settings to the "Search patterns" section and tick off usage of german (and any other) patterns you are not interested in.

**Comment by shanerooks** [comment]
Additionally, fully typing out "Black Morass" lists the post as being for the Black Temple raid.

**Comment by Vysci** [comment]
What "the-chuppa" said. Please turn off other languages, this is intended behavior
