### ISSUE TITLE
Cannot save filter changes in TBC Classic

### ISSUE THREAD

**Issue by Feelgoodinc93** [Vysci/LFG-Bulletin-Board#109]
When going into the configuration window for LFG Bulletin Board, I am able to check or uncheck the boxes for any particular dungeons I want the addon to search for, however, once I click okay and return to the main addon screen, it has not saved any of my filter changes. Upon returning to the configuration screen, the boxes I previously checked or unchecked have not been saved upon clicking okay. 

I have tried to delete the folder and reinstall the addon. I have tried to manually add the addon to my game folder, and I have had a friend send me their addon in a zip file and tried that one. None of them have worked. I have recently seen a comment on the pain addon curseforge page that details a similar issue as I am having. I'm still not sure if its another addon interference or just a bug,

**Comment by Vysci** [comment]
Is there any particular actions you can think of that led to it happening ? I seen a small amount of mentions of this issue but I cannot reproduce. Any details you can share would be helpful

**Comment by MightBeChris** [comment]
I got an error today as this issue started happening to me.  Message: Interface\AddOns\LFGBulletinBoard\RequestList.lua:341: invalid order function for sorting
Time: Sun Jul 18 16:43:24 2021
Count: 1
Stack: Interface\AddOns\LFGBulletinBoard\RequestList.lua:341: invalid order function for sorting
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface\AddOns\LFGBulletinBoard\RequestList.lua"]:341: in function `UpdateList'
[string "@Interface\AddOns\LFGBulletinBoard\RequestList.lua"]:732: in function `PhraseMessage'
[string "@Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua"]:666: in function `?'
[string "@Interface\AddOns\LFGBulletinBoard\LibGPIToolBox.lua"]:100: in function <Interface\AddOns\LFGBulletinBoard\LibGPIToolBox.lua:97>

Locals: errMsg = "Interface\AddOns\LFGBulletinBoard\RequestList.lua:341: invalid order function for sorting"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}


Can't tell if this is TSM or you.

**Comment by Vysci** [comment]
It looks like TSMs variables scope is too broad and impacting this add on. I’ll check to see if I can rename the variables to avoid collision

**Comment by MightBeChris** [comment]
The current workaround is to edit the setting file in the WTF folder.  It's annoying but functional.

**Comment by Chumanoyasha** [comment]
Same here, can't change filters! Got no TSM addon.

**Comment by Chumanoyasha** [comment]
Just fixed it for myself. For me it was ChatAssistant addon that was not letting me to save any filter changes / settings!
