### ISSUE TITLE
Incompatibility with Titan Panel Classic. Need to join LFG channel to use bulletin board and timestamps not showing.

### ISSUE THREAD

**Issue by kehcount** [Vysci/LFG-Bulletin-Board#113]
**Describe the bug**
I can no longer see timestamps for how long an LFG message has been active, I only see "msgTimeFo.." and when I scroll over it it says "msgTotalTime". 
I can no longer see messages on the bulletin board without joining the lfg channel. Before, I was able to see lfg messages without having to see the spam in my chatbox. 
In mode type (heroic vs normal) - it now says [normalAbr] or [heroicAbr] instead of just [N] and [H] 
When I go to type in the chatbox, I have to delete the default text "Enter here your lfg message" Instead of it just deleting itself to let me type.

**To Reproduce**
Not sure how this happened. It was working fine, I joined a group and when I went to Caverns of Time I realized it wasn't working properly anymore.

**Expected behavior**
I should be able to see timestamps.
I should be able to see messages in the bulletin board without actually joining the lfg channel.

**Screenshots**
![World Of Warcraft - Classic Screenshot 2021 07 06 - 15 17 37 97 (2)](https://user-images.githubusercontent.com/87038883/124655177-82ab5480-de6d-11eb-884c-55511404806d.png)
![World Of Warcraft - Classic Screenshot 2021 07 06 - 15 22 38 76 (2)](https://user-images.githubusercontent.com/87038883/124655648-1f6df200-de6e-11eb-9bdb-000fc403318a.png)

**Desktop (please complete the following information):**
 - Windows 10 updated.
 - Ryzen 3600 @4.2GHz
 - GTX 1070 Ti
 - 32 GB 3000MHz DDR4 RAM
 - B350 ASUS ROG STRIX Motherboard

**Comment by kehcount** [comment]
I just deactivated the last addon I added - Titan Panel Classic. It seems this has messed up something with the LFG bulletin board and they are not compatible addons.

**Comment by Vysci** [comment]
lol sorry for the desktop section it's what add-on version are you running. Is this still an issue with the latest 2.59 update?

**Comment by kehcount** [comment]
Yes, it's fixed now! Thank you
