### ISSUE TITLE
No chatbox since latest update

### ISSUE THREAD

**Issue by kehcount** [Vysci/LFG-Bulletin-Board#118]
**Describe the bug**

Should be able to post in the LFG bulletin window with the chatbox, but there is no chatbox anymore.

**Screenshots**
![WoWScrnShot_071021_185850](https://user-images.githubusercontent.com/87038883/125178267-320b6280-e1b1-11eb-878d-1481476776e2.jpg)

**Expected behavior**

Being able to post on the LFG chat through the bulletin window

**Screenshot of how chatbox should appear**
![World Of Warcraft - Classic Screenshot 2021 07 06 - 15 22 38 76 (3)](https://user-images.githubusercontent.com/87038883/125178331-c1b11100-e1b1-11eb-9dc8-0e93f4651cad.png)

**Comment by Vysci** [comment]
Go to options and check display lfg bar
