### ISSUE TITLE
Latest update has stopped it working altogether

### ISSUE THREAD

**Issue by SmallerGaia** [Vysci/LFG-Bulletin-Board#119]
Last night the bulletin board was filled based on my filters and working perfectly.

But i installed the latest update just this morning and it now seems to fail to pick up anything from the chat, unsure what changed but its broken something :)

**Comment by Vysci** [comment]
Do you have "Filter by level range" disabled?

**Comment by SmallerGaia** [comment]
Yes it is disabled.

**Comment by Vysci** [comment]
Well you have normal filter and heroic filter selected, which means you are only filtering raids but you have no raids selected

**Comment by SmallerGaia** [comment]
Ah I see, I think I used to have them both on before, or maybe i just messed with them and broke it..

But turning them both off got me what I wanted! Thank you!
