### ISSUE TITLE
Custom Filter

### ISSUE THREAD

**Issue by Lipovske** [Vysci/LFG-Bulletin-Board#120]
**Describe the solution:**

When trying to create a custom filter to only show when, for instance, somebody asks for a healer. I assumed if I put healer, heals, heal in the "Search words" filter it would filter message by that filter first and then go down and sort them by the heroic and dungeon keywords, but that does not seem to be how it works. 

I would like it to work like that to allow me to create a custom filter for dungeons, and more specifically heroic dungeons that only I can fill. 

**I could work around this by putting Tank/DPS on the blacklist but that seems like a less than elegant solution to a problem that could be solved by what I describe above.** 

Also no save button on the custom filtering options is very annoying I had to go back and type in so many. Please just add a button to copy the search filters from the other lists.

**Comment by Vysci** [comment]
You can take a look at the curseforge page for a detailed explanation on how custom search patterns work. If I understood you correctly, It should include an explanation how to accomplish what you were trying to do 
Can you elaborate on the save button? Not sure what you mean

**Comment by Lipovske** [comment]
Ok I will check out the documentation and see if it solves my problems.

By a save button I just mean that having to type in all the filters for the
different dungeons and raids to create a custom filter was an issue. Maybe
I missed an easy way to do this but when I eventually just retyped all the
English filters line by line a few of them wouldn't save in my custom
filter after I exited and reentered the editor.

I am just proposing a way to easily import the English or other default
filters onto lines that you do not want to change when creating a custom
filter.

Thanks

**Comment by Lipovske** [comment]
**Custom Search Pattern issues

    There is a bit of confusion on how it works which leads people to believe there is a bug. It basically works like this:

         1.  Languages + custom selected: this will result in using all of the languages default values AND anything that has been entered manually

         2. Only custom selected: it will override with the values have been entered. If fields were left blank then the value is blank

         3. Only 1 language selected: it will use the languages default values and ignore anything that has been entered**


Is this what you were referring to on curseforge? that does not solve my problem. I want the custom filter to let me apply one filter to all messages and then another filter to separate the ones that get through the first filter to separate them by dungeon.

Thanks
