### ISSUE TITLE
Custom blacklist not working

### ISSUE THREAD

**Issue by OnceWasPerfect** [Vysci/LFG-Bulletin-Board#123]
**Describe the bug**
Text entered in Blacklist words is not being filtered out.

**To Reproduce**
Enter text in Blacklist words (wts or boost for example) and make sure custom is checked.

**Expected behavior**
Posts with those words to be filtered. 

**Screenshots**
See screen shot with settings and LFG window open attached

**Desktop (please complete the following information):**
 - Version 2.60 TBC

**Additional context**
I disabled all my other addons to test hence the ugly UI in the screen shot. 
![WoWScrnShot_080821_053854](https://user-images.githubusercontent.com/53492647/128627779-fc1c3068-7dbd-446e-a433-7eec1c230537.jpg)

**Comment by Friiar** [comment]
it seems like you can filter boost but if you are looking for slave pens, that over rides and shows the statement.

**Comment by hglbrg** [comment]
It does work if you hit ENTER while the text field is active. Leads me to believe that it doesn't react to losing focus but just keyDown Enter or something. 

So fill out your words... hit enter while the cursor is active in the text field and it works

**Comment by juemrami** [comment]
Reported on CF:
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=663
