### ISSUE TITLE
BM listings under Ramparts

### ISSUE THREAD

**Issue by jazminite** [Vysci/LFG-Bulletin-Board#124]
## Describe the bug
Listings for BM show under Ramparts

## To Reproduce
Open addon in-game and wait for someone to post `LFG BM...`

## Expected behavior
Listing should appear under Black Morass

## Screenshots
![BM](https://i.imgur.com/6hTQgvP.png)

## Desktop
 - Version 2.59

## Additional context
N/A

**Comment by Vysci** [comment]
Not a bug. Uncheck other languages under "Search patterns"
