### ISSUE TITLE
fps drop

### ISSUE THREAD

**Issue by hamedwar** [Vysci/LFG-Bulletin-Board#137]
Sometimes when I open the addon, fps drop and the game is lagged

**Comment by ssateneth** [comment]
Please look into this. The lag is most apparent when on a busy server whenever someone advertises a dungeon boosting service. For example, it seems any mage that advertises "WTS SP BOOST" will cause the game client to stutter, lag, or freeze up entirely for seconds at a time. It happens for other dungeons that people like to boost like stratholme, stockages, you name it. I can't use the addon at all without lag.

Tried with zero addons enabled, and deleted the WTF addon settings folder, no change. My computer isn't slow either; It's a Ryzen 9 5950x, 128GB of DDR4-3800MHz CAS14 RAM, RTX 3090, and Intel Optane 905P SSD. Nothing here should be bottlenecking the game or causing problems.

**Comment by mrAndersen** [comment]
Lagg is confirmed, everyone actually has this, but ppl can't really determine the source of that lag, but disabling LFG Group Bulletin Board DO fixes the problem.

**Comment by juemrami** [comment]
closing this as completed. A new thread should be opened whenever there are more performance issues.
