### ISSUE TITLE
Filter that will exclude posts.

### ISSUE THREAD

**Issue by maiekkk** [Vysci/LFG-Bulletin-Board#138]
This is related to current situation where there are more boosters than normal players and you have to deal with boosting services spam.

It would be a nice feature if you add word blacklist, so if the announcement contain blacklisted word will be instantly excluded from the results. (if you just blacklist "boost" the whole announcement won't be shown in the bulletin board). 

Best regards.

**Comment by demokert** [comment]
Yes please!

**Comment by Vysci** [comment]
This is an already existing feature in the settings, there is a section “blacklist” where you can enter blacklisted words

**Comment by demokert** [comment]
Thanks for pointing this out! Not sure how i missed this :D
