### ISSUE TITLE
Can't change settings in the filter.

### ISSUE THREAD

**Issue by Serocrux1** [Vysci/LFG-Bulletin-Board#147]
I can't seem to turn off "Normal only" filter in TBC or change any other settings for that matter. I click on them, go out of the program and when I check nothing's changed.

https://gyazo.com/a853944ac7817bee53a117ae3a5784d7

I'm on V2.62, fresh and updated.
I've tried both removing it and redownloading it upon new and reinstalling it through curseforge but it won't work, please help.

**Comment by juemrami** [comment]
related to #200
