### ISSUE TITLE
Implement minimap button with LibDBIcon

### ISSUE THREAD

**Issue by gabbsmo** [Vysci/LFG-Bulletin-Board#150]
I reported an [issue if LFG Bulletin Board](url) in Sexymap where it would not be hidden until mouseover like other addon buttons. I got the reply that the minimap button needs to be implemented using LibDBIcon to play nice with other addons.

**Comment by juemrami** [comment]
We dont have "full" `LibDBIcon` support but with #302 , you should be able to take advantage of LibDBIcon if you have any other addon that does use it (sexymaps likely bundles it) then you should be able to take advantage of it.
