### ISSUE TITLE
WotLK Filter options panel select/unselect all buttons are not working.

### ISSUE THREAD

**Issue by mnejing** [Vysci/LFG-Bulletin-Board#155]
Not sure if you want a proper bug report, but I just downloaded the most recent updates from the repo here, and tried the select and unselect all buttons on the WotLK filter panel. Checked Options.lua and it's just a copy and paste that wasn't updated. 

`	GBB.Options.AddButton(GBB.L["BtnSelectAll"],function()
	DoSelectFilter(true, WotlkChkBox_FilterDungeon, GBB.WOTLKDUNGEONSTART, GBB.WOTLKMAXDUNGEON-2) -- Doing -2 to not select trade and misc
	end)
	GBB.Options.AddButton(GBB.L["BtnUnselectAll"],function()
	DoSelectFilter(false, WotlkChkBox_FilterDungeon, GBB.WOTLKDUNGEONSTART, GBB.WOTLKMAXDUNGEON)
	end)`

Seems to do the trick.

**Comment by Vysci** [comment]
Should be resolved
