### ISSUE TITLE
Frame strata setting causes visibility issues.

### ISSUE THREAD

**Issue by sjpfeiffer** [Vysci/LFG-Bulletin-Board#16]
![image](https://user-images.githubusercontent.com/14336807/120894695-ab220380-c5ce-11eb-8136-8d5a2ab8833c.png)
Recommend setting frame strata to HIGH in GroupBulletinBoard.xml to prevent issues like seen above.

**Comment by sjpfeiffer** [comment]
![image](https://user-images.githubusercontent.com/14336807/120894742-ddcbfc00-c5ce-11eb-8f64-3f3a663df86c.png)
Here's the window's appearance after setting frame strata to medium

**Comment by Vysci** [comment]
You are right it looks better. Since you did the change why not make a pull request?
