### ISSUE TITLE
Unable to identify Naxx as tag

### ISSUE THREAD

**Issue by Schm1dt1304** [Vysci/LFG-Bulletin-Board#162]
Im trying to advertise for a Naxx run comming up once raids open, however the addon is unable to identify naxx as an option.

**Comment by Vysci** [comment]
This is because I forgot that Naxx is also a vanilla raid, hence it’s getting caught under the vanilla naxx. I will fix this, in the mean time you can select naxx under vanilla filters

**Comment by Vysci** [comment]
Should be fixed
