### ISSUE TITLE
LookingForGroup Bug Conflict

### ISSUE THREAD

**Issue by Landate** [Vysci/LFG-Bulletin-Board#163]
**Describe the bug**
When creating an application in the LFG Tool Group Finder, the addon breaks the group viewing system and for this you can not see the groups here is an error
```
22x [ADDON_ACTION_BLOCKED] Modification 'LFGBulletinBoard' tried to call protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>
```

**To Reproduce**
1. Go to 'Group Finder (LookingForGroup)'
2. Click on 'add to the list(make group witch options)'
3. Scroll down to 'to advertise(Make group)'

**Expected behavior**
Fix the problem

**Screenshots**
![Imgae](https://user-images.githubusercontent.com/45266432/194050013-59e72b5e-c9af-4e82-b983-bbbee1df400e.png)

**Desktop (please complete the following information):**
 - Version [e.g. v2.48] Last version

**Additional context**

**Comment by raimondi1337** [comment]
Also have this error

**Comment by Vysci** [comment]
Should be fixed now

**Comment by Vysci** [comment]
> 

Are you by any chance using Global Ignore addon (forgot that name but something like that)? I know that there are a couple add-ons that cause that issue. If not can you confirm that this issue only happens when bulletin board is the only add-on enabled?

**Comment by Landate** [comment]
> > Î still have this issue, so it does not seem to be fixed. Can't use the lfg tool when bulletin board is enabled (most of the time a reload makes it work for a while but not long)
> 
> Are you by any chance using Global Ignore addon (forgot that name but something like that)? I know that there are a couple add-ons that cause that issue. If not can you confirm that this issue only happens when bulletin board is the only add-on enabled?

Unfortunately, I had to abandon your addon, as it will significantly reduce performance and short-term freezes appear in the raid, which is solved by restarting the game, but not for a long time.
