### ISSUE TITLE
Group finder displays only "searching"

### ISSUE THREAD

**Issue by antonisgkamitsios** [Vysci/LFG-Bulletin-Board#173]
Some times when i will start a listing on the group finder a message on the chat pops "Interface action failed because of an addon" and the group finder is stuck on "searching" untill i reload ui. I downloaded bug sack to see what was the cause of this error and i got these reuslts
2x [ADDON_ACTION_BLOCKED] AddOn 'LFGBulletinBoard' tried to call the protected function 'Search()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>

**Comment by Toodo** [comment]
i also got this problem i open group finder then group browser select an dungeon open bulletin go on tool requests then group finder break so it just say searching... . im on wow wotlk classic 3.4.2

```
1x [ADDON_ACTION_BLOCKED] AddOn 'LFGBulletinBoard' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:226: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:214: in function `LFGBrowseSearchButton_OnClick'
[string "*Blizzard_LFGBrowse.xml:424_OnClick"]:2: in function <[string "*Blizzard_LFGBrowse.xml:424_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:765: in function `Entry'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:114: in function <LFGBulletinBoard/LibGPIToolBox.lua:112>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```
