### ISSUE TITLE
lua error, broken addon

### ISSUE THREAD

**Issue by ssateneth** [Vysci/LFG-Bulletin-Board#175]
**Describe the bug**
lua error, addon broken

**To Reproduce**
load the game
get error

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/2127021/213046810-819f4454-1ebf-4a01-a31b-37b5337d2c7c.png)

**Desktop (please complete the following information):**
3.09

**Additional context**
i dont know, the addon is broken

**Comment by Vysci** [comment]
Hopefully fixed now
