### ISSUE TITLE
Profession links always pop up when passing over them

### ISSUE THREAD

**Issue by legolas-a20** [Vysci/LFG-Bulletin-Board#177]
When a profession link like [Blacksmithing] ends up in the LFG board, the profession opens whenever the mouse cursor passes over it. I'm not sure what causes this, but it's annoying (especially because it also causes my bags to open).

Would an option to not have this be possible? Or, if not, replace them by text instead of the linked profession as a workaround, a bit like the option to not remove raid symbols?

**Comment by dieck** [comment]
Same here, quite annoying, would be much better if that could open on click, not on mouse over.

I started looking into the code, but I wasn't able to find the right place yet.

**Comment by juemrami** [comment]
Fix in 3.31
