### ISSUE TITLE
Boost filter

### ISSUE THREAD

**Issue by Sebbyyy** [Vysci/LFG-Bulletin-Board#179]
Could you just create a section for boosts of each instance in classic etc? I feel it would help to declutter the bulletin board

**Comment by juemrami** [comment]
I plan on creating a system where you can add your own Categories and configure the keywords for it and whether or not it's an exclusive category.

Nothing on paper yet, still working out other bits of the codebase before i get around to that.

**Comment by Alessandro-Barbieri** [comment]
> > looks like boosts aren't correctly filtered out
> 
> Ty for reporting ill check this out, questions first though.
> 
>     1. Is your goal here to:
> 
> 
>     * **A**: Hide all message with the keyword `boost` in it?
> 
>     * **B**: Group all message with the keyword `boost` into its own category?

I want to hide boost messages

 
>     2. What locales (languages) do you have enabled for the addon?
english and custom

**Comment by juemrami** [comment]
Okay. This can be manages with the "Blacklist Words" addon setting, any keywords there will be automatically filtered out. `layer` is the only default one added by the addon, you can add more by editing the text box (see image)

![image](https://github.com/user-attachments/assets/9a62becf-fb9e-4fe2-a404-97dd700f45d3)
