### ISSUE TITLE
Player's realms are not included in their names which breaks much of the addon's functionality

### ISSUE THREAD

**Issue by keeehlan** [Vysci/LFG-Bulletin-Board#180]
Without including realms in character names, I can't use many of the convenient features in the addon without manually checking the LFG channel for the poster.

**Comment by juemrami** [comment]
Recently fixed in #237, commit [5b71d54](https://github.com/Vysci/LFG-Bulletin-Board/pull/237/commits/5b71d54acb70fd56d1b2a022f3365222e66a6e44)

Will only show realm names for characters on a different realm when the "Always Remove Realm" option is *un*checked
