### ISSUE TITLE
LFGBrowseFrame is nil - Classic Era

### ISSUE THREAD

**Issue by Edder** [Vysci/LFG-Bulletin-Board#181]
**Describe the bug**
Error message when clicking on LfgTool tab because LFGBrowseFrame (official Blizzard LFG Tool) doesn't exist on Classic Era clients.

**To Reproduce**
1. Log on Classic Era
2. Open LFG Bulletin Board
3. Click on LfgTool tab

**Expected behavior**
No error and maybe remove the LfgTool tab, as it does not make sense on Classic Era.

**Error message**
160x Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:241: attempt to index global 'LFGBrowseFrame' (a nil value)
[string "@Interface\AddOns\LFGBulletinBoard\LfgToolList.lua"]:241: in function `UpdateLfgToolNoSearch'
[string "@Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua"]:748: in function `Entry'
[string "@Interface\AddOns\LFGBulletinBoard\LibGPIToolBox.lua"]:114: in function <Interface\AddOns\LFGBulletinBoard\LibGPIToolBox.lua:112>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LFGBrowseFrame' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:142
 CreateTagList = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:288
 GetDungeonNames = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:15
 ClearNeeded = false
 InitGroupList = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupList.Lua:175
 TBCMAXDUNGEON = 56
 LfgRequestHideTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:737
 tagList = <table> {
 }
 suffixTags = <table> {
 }
 LevelRange = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:116
 ParseMessage = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:641
 LFG_Successfulljoined = true
 ClearTimer = 1723099397
 UpdateLfgToolNoSearch = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:240
 VanillaDungeonLevels = <table> {
 }
 NotifySound = 1210
 PostTbcDungeonLevels = <table> {
 }
 MiniIcon = "Interface\Icons\spell_holy_prayerofshadowprotection"
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:793
 ClickFrame = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:836
 CreateChatFrame = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:232
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:717
 WOTLKDUNGEONSTART = 57
 dungeonSecondTags = <table> {
 }
 SplitNoNb = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:59
 TAGBAD = "---"
 VanillDungeonNames = <table> {
 }
 GetDungeonSort = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:753
 TBCDUNGEONSTART = 32
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @Interface\AddOns\LFGBulletinBoard\Localization.lua:728
 Popup_Minimap = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:366
 ClickDungeon = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:843
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 Raids = <table> {
 }
 RequestShowTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:883
 ClickRequest = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:860
 AllowInInstance = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:46
 MSGPREFIX = "GBB: "
 UpdateLfgTool = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:216
 OptionsUpdate = <function> defined @Interface\AddOns\LFGBulletinBoard\Options.lua:67
 Announce = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:140
 LFG_UPDATETIME = 10
 PvpNames = <table> {
 }
 BtnSelectChannel = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:172
 LfgRequestShowTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:688
 GetRaids = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:728
 L = <table> {
 }
 ElapsedSinceListUpdate = 1.001000
 Init = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:395
 ElapsedSinceLfgUpdate = 18.315001
 RequestList = <table> {
 }
 LFG_Timer = 1691562968
 RaidList = <table> {
 }
 locales = <table> {
 }
 TBCDUNGEONBREAK = 50
 CreateTagListLOC = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:252
 InsertChat = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:49
 Clear = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:328
 CreateChannelPulldown = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:149
 LfgClickRequest = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:657
 UserName = "Heino"
 PatternWho1 = "|Hplayer:(.-)|h%[(.

**Comment by drum84** [comment]
Yup same, unfortunately. Could you look into it, if you find the time? Thank you very much <3

`1x Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:217: attempt to index global 'LFGBrowseFrame' (a nil value)
[string "@Interface\AddOns\LFGBulletinBoard\LfgToolList.lua"]:217: in function `UpdateLfgTool'
[string "@Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua"]:215: in function `ShowWindow'
[string "@Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua"]:228: in function `ToggleWindow'
[string "@Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua"]:529: in function `onClick'
[string "@Interface\AddOns\LFGBulletinBoard\LibGPIMinimapButton.lua"]:66: in function <...face\AddOns\LFGBulletinBoard\LibGPIMinimapButton.lua:63>
[string "=[C]"]: in function `Click'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus-1.14.121.lua"]:5338: in function `OnClick'
[string "@Interface\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0-52.lua"]:170: in function <...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:168>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LFGBrowseFrame' (a nil value)"
LastUpdateTime = 1692624489
GBB = <table> {
 GetLfgList = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:142
 CreateTagList = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:288
 GetDungeonNames = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:15
 ClearNeeded = false
 InitGroupList = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupList.Lua:175
 TBCMAXDUNGEON = 56
 LfgRequestHideTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:735
 tagList = <table> {
 }
 suffixTags = <table> {
 }
 LevelRange = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:116
 ParseMessage = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:641
 LFG_Successfulljoined = true
 ClearTimer = 1692634481.228000
 UpdateLfgToolNoSearch = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:238
 VanillaDungeonLevels = <table> {
 }
 NotifySound = 1210
 PostTbcDungeonLevels = <table> {
 }
 MiniIcon = "Interface\Icons\spell_holy_prayerofshadowprotection"
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:793
 ClickFrame = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:836
 CreateChatFrame = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:232
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:713
 WOTLKDUNGEONSTART = 57
 dungeonSecondTags = <table> {
 }
 SplitNoNb = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:59
 TAGBAD = "---"
 VanillDungeonNames = <table> {
 }
 GetDungeonSort = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:753
 TBCDUNGEONSTART = 32
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @Interface\AddOns\LFGBulletinBoard\Localization.lua:728
 Popup_Minimap = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:366
 ClickDungeon = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:843
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 Raids = <table> {
 }
 RequestShowTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:883
 ClickRequest = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:860
 AllowInInstance = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:46
 MSGPREFIX = "GBB: "
 UpdateLfgTool = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:216
 OptionsUpdate = <function> defined @Interface\AddOns\LFGBulletinBoard\Options.lua:67
 Announce = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:140
 LFG_UPDATETIME = 10
 PvpNames = <table> {
 }
 BtnSelectChannel = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:172
 LfgRequestShowTooltip = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:686
 GetRaids = <function> defined @Interface\AddOns\LFGBulletinBoard\Dungeons.lua:728
 L = <table> {
 }
 ElapsedSinceListUpdate = 0.733000
 Init = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:395
 ElapsedSinceLfgUpdate = 9989.652519
 RequestList = <table> {
 }
 LFG_Timer = 1692624521
 RaidList = <table> {
 }
 locales = <table> {
 }
 TBCDUNGEONBREAK = 50
 CreateTagListLOC = <function> defined @Interface\AddOns\LFGBulletinBoard\GroupBulletinBoard.lua:252
 InsertChat = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:49
 Clear = <function> defined @Interface\AddOns\LFGBulletinBoard\RequestList.lua:328
 CreateChannelPulldown = <function> defined @Interface\AddOns\LFGBulletinBoard\Chat.lua:149
 LfgClickRequest = <function> defined @Interface\AddOns\LFGBulletinBoard\LfgToolList.lua:655`
