### ISSUE TITLE
I see each post twice (See picture)

### ISSUE THREAD

**Issue by Suupaah** [Vysci/LFG-Bulletin-Board#185]
(https://github.com/Vysci/LFG-Bulletin-Board/assets/70293127/295a24d4-829c-463c-9e4b-81c82a7e1970)
I'm not sure if this a bug or not.
But for some reason the addon thinks someone is posting twice one time under their normal name and one time under their name-realm.

**Comment by Vysci** [comment]
Should be resolved now
