### ISSUE TITLE
Lua error when clicking on the Tool Request button

### ISSUE THREAD

**Issue by Pocokk** [Vysci/LFG-Bulletin-Board#190]
**Describe the bug**
Endless lua error spam 

**To Reproduce**
1) Open Premade Group Finder 
2) Click on the Tool Request button at the bottom

 
 - Version: latest stable 3.12

**Additional context**
Error itself:

296x LFGBulletinBoard/LfgToolList.lua:239: attempt to index global 'LFGBrowseFrame' (a nil value)
[string "@LFGBulletinBoard/LfgToolList.lua"]:239: in function `UpdateLfgToolNoSearch'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:756: in function `Entry'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:114: in function <LFGBulletinBoard/LibGPIToolBox.lua:112>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LFGBrowseFrame' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @LFGBulletinBoard/LfgToolList.lua:142
 CreateTagList = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:293
 GetDungeonNames = <function> defined @LFGBulletinBoard/Dungeons.lua:15
 ClearNeeded = false
 InitGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:175
 TBCMAXDUNGEON = 56
 LfgRequestHideTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:735
 tagList = <table> {
 }
 suffixTags = <table> {
 }
 LevelRange = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:116
 ParseMessage = <function> defined @LFGBulletinBoard/RequestList.lua:641
 LFG_Successfulljoined = true
 ClearTimer = 1697633361.629000
 UpdateLfgToolNoSearch = <function> defined @LFGBulletinBoard/LfgToolList.lua:238
 VanillaDungeonLevels = <table> {
 }
 NotifySound = 1210
 PostTbcDungeonLevels = <table> {
 }
 MiniIcon = "Interface\Icons\spell_holy_prayerofshadowprotection"
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:794
 ClickFrame = <function> defined @LFGBulletinBoard/RequestList.lua:837
 CreateChatFrame = <function> defined @LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:237
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:725
 WOTLKDUNGEONSTART = 57
 dungeonSecondTags = <table> {
 }
 SplitNoNb = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:59
 TAGBAD = "---"
 VanillDungeonNames = <table> {
 }
 GetDungeonSort = <function> defined @LFGBulletinBoard/Dungeons.lua:753
 TBCDUNGEONSTART = 32
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @LFGBulletinBoard/Localization.lua:728
 Popup_Minimap = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:371
 ClickDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:844
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 Raids = <table> {
 }
 RequestShowTooltip = <function> defined @LFGBulletinBoard/RequestList.lua:884
 ClickRequest = <function> defined @LFGBulletinBoard/RequestList.lua:861
 AllowInInstance = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:46
 MSGPREFIX = "GBB: "
 UpdateLfgTool = <function> defined @LFGBulletinBoard/LfgToolList.lua:216
 OptionsUpdate = <function> defined @LFGBulletinBoard/Options.lua:67
 Announce = <function> defined @LFGBulletinBoard/Chat.lua:140
 LFG_UPDATETIME = 10
 PvpNames = <table> {
 }
 BtnSelectChannel = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:172
 LfgRequestShowTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:686
 GetRaids = <function> defined @LFGBulletinBoard/Dungeons.lua:728
 L = <table> {
 }
 ElapsedSinceListUpdate = 1.004000
 Init = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:400
 ElapsedSinceLfgUpdate = 423.991011
 RequestList = <table> {
 }
 LFG_Timer = 1697632906
 RaidList = <table> {
 }
 locales = <table> {
 }
 TBCDUNGEONBREAK = 50
 CreateTagListLOC = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:257
 InsertChat = <function> defined @LFGBulletinBoard/Chat.lua:49
 Clear = <function> defined @LFGBulletinBoard/RequestList.lua:328
 CreateChannelPulldown = <function> defined @LFGBulletinBoard/Chat.lua:149
 LfgClickRequest = <function> defined @LFGBulletinBoard/LfgToolList.lua:655
 UserName = "Ishimura"
 PatternWho1 = "|Hplayer

**Comment by Pocokk** [comment]
Update: turns out I can reproduce the issue simply clicking on the Tool Request button at the bottom.

**Comment by juemrami** [comment]
same issue as #181, this was fixed to not error but the tab has been overall disabled since the Activity finder has changed and that module requires a rework.
