### ISSUE TITLE
WoW Classic Era - Onyxia missing in Vanilla Filter

### ISSUE THREAD

**Issue by maximus210793** [Vysci/LFG-Bulletin-Board#194]
Hi,

Onyxia is missing in the Vanilla Filter.

Please add it.
Thank you!

**Comment by arthurlaengle** [comment]
Onyxia does not show up ion classic era bulletin board. Please fix this. I think its a bug.

**Comment by juemrami** [comment]
Fixed in #236, these changes should be reflected in the current beta/alpha build on curseforge. Will update official release soon.

**Comment by juemrami** [comment]
fixed in 3.3
