### ISSUE TITLE
[Classic SoD] Scarlet monastery parsing broken

### ISSUE THREAD

**Issue by DocNessuno** [Vysci/LFG-Bulletin-Board#201]
**Describe the bug**
All instances of Scarlet Monastery show up under Scarlet Monastery:Armory regardless of wing-specific keywords.

**To Reproduce**
- Play WoW classic SoD
- Have English localization selected as search pattern
- cheek LFG bulletin board for Scarlet Monastery

**Expected behavior**
Each SM wing is properly shown under the appropriate heeding.

**Screenshots**
[Here](https://i.imgur.com/5wUgzTY.png)

**Desktop (please complete the following information):**
 Version: Classic 3_14

**Additional context**
Shortly after opening the add-on a Blizzard "many errors" warning appears. (errors reported below)
Issue presents itself also in a profile with no other addon loaded.
When collapsing the armory group, the listing within remain visible.

**Comment by DocNessuno** [comment]
`Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
Time: Sat Feb 24 10:57:39 2024
Count: 2
Stack: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:133: in function `FilterDungeon'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:437: in function `UpdateList'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:221: in function `ShowWindow'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:233: in function `ToggleWindow'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:534: in function `onClick'
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIMinimapButton.lua"]:66: in function <...face/AddOns/LFGBulletinBoard/LibGPIMinimapButton.lua:63>
[string "=[C]"]: in function `Click'
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:5220: in function `OnClick'
[string "@Interface/AddOns/ItemRack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:170: in function <...AddOns/ItemRack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1
`
`Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
Time: Sat Feb 24 10:56:38 2024
Count: 5
Stack: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:133: in function `FilterDungeon'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:437: in function `UpdateList'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:857: in function `ClickDungeon'
[string "*GroupBulletinBoard.xml:273_OnMouseDown"]:1: in function <[string "*GroupBulletinBoard.xml:273_OnMouseDown"]:1>

Locals: (*temporary) = "LeftButton"
(*temporary) = <function> defined =[C]:-1
`
`Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
Time: Sat Feb 24 10:58:48 2024
Count: 7325
Stack: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:133: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:133: in function `FilterDungeon'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:437: in function `UpdateList'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:754: in function `Entry'
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua"]:114: in function <Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua:112>

Locals: (*temporary) = 0.011000
(*temporary) = <function> defined =[C]:-1
`

**Comment by Adondriel** [comment]
[Classic SoD] I have a bit of a different issue. I have the most recent classic version of this addon from Curse. ALL Scarlet Monastery dungeons are "uncategorized" or the group header is not shown properly. resulting in this: 
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/1113496/44766f50-6b1a-4eaf-9afb-738ea9213ae1)

I think the header group just isnt being rendered properly? Let me know if this should be a separate ticket.

**Comment by Vysci** [comment]
Hmmm this is weird. @Adondriel mind taking a screenshot of search patterns page ?

**Comment by Adondriel** [comment]
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/1113496/ae30e76e-64de-4bb5-abe0-b712841eb93d)
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/1113496/829780bc-fcb8-42d8-a27f-260891ae34a5)
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/1113496/d349638b-9d49-47e1-b352-14e98d5a9b43)
@Vysci Grabbed all the ones the seem relevant to SM. All are the default english values

**Comment by Vysci** [comment]
@Adondriel do you have the "Combine sub-dungeons like Dire Maul" checkbox ticked? 
![Capture](https://github.com/Vysci/LFG-Bulletin-Board/assets/84870873/68b19de6-9244-4c56-8c75-2c0a6eb4b50c)

**Comment by Adondriel** [comment]
@Vysci Yes, that checkbox is ticked.

**Comment by Vysci** [comment]
@Adondriel I suggest having it unchecked. I think the bug is caused by it. It's not super obvious at first glance

**Comment by Adondriel** [comment]
> @Adondriel I suggest having it unchecked. I think the bug is caused by it. It's not super obvious at first glance

yep, confirmed it is working after unchecking that

**Comment by DocNessuno** [comment]
> @Adondriel I suggest having it unchecked. I think the bug is caused by it. It's not super obvious at first glance

@Vysci Unchecking that box also resolved my issue.

**Comment by juemrami** [comment]
looking into this atm 👍
