### ISSUE TITLE
Arathi Basin request shown under miscellaneous

### ISSUE THREAD

**Issue by B2SquareOne** [Vysci/LFG-Bulletin-Board#204]
**Describe the bug**
I turned on the category "Arathi Basin", still when people write in world/lfg Chat text's with "AB" or "Arathi" is shown under the miscellaneous section.

Im playing SoD and using the 3.17 (newest) version. 
To add customizable Battleground search terms in the options would solve this.

**Comment by juemrami** [comment]
Seems like "arathi" is not a default english tag for it, only "ab" and "basing". Meaning messages that only match "arathi" in its body will get sorted to Miscellaneous. This prevents general messages w/ the word "arathi" in them from getting catagorised as part of "Arathi Basin" request. 

If you want, you could add "arathi" to the "Search Patterns" panel entry for Arathi Basin in the ingame addons settings.
