### ISSUE TITLE
Possible to "flood" board

### ISSUE THREAD

**Issue by tjeaton** [Vysci/LFG-Bulletin-Board#21]
Hi never posted an issue before so thought I'd give it ago.

Saw this addon and think it is absolutely amazing, however i have noticed if you essentially enter the keyword for each instance in a single message then essentially you will appear multiple times within the board list.

I am wondering if it is possible to limit to 3 dungeons per person maybe? Not sure if possible or not?

This image below should hopefully explain a little better whats happening?

![image](https://user-images.githubusercontent.com/3155588/121225103-198dec80-c881-11eb-9023-979375349905.png)

**Comment by Vysci** [comment]
This is going to be either low priority or will not fix at this time, as most people filter for a few dungeons the flood will be limited to those dungeons. If this continues to be an issue though will revisit this

**Comment by Vysci** [comment]
Please reopen if becomes a bigger issue
