### ISSUE TITLE
Add option to not close window with ESC key

### ISSUE THREAD

**Issue by chrishenzie** [Vysci/LFG-Bulletin-Board#216]
By default, when you hit ESC it closes the LFG Bulletin Board window. Having to re-type `/gbb` repeatedly can get annoying when you're playing and browsing simultaneously and want to keep the window open.

It would be really helpful if we could have an option for not closing the window when ESC is closed. By default it can stay off to provide the same UX.

**Comment by juemrami** [comment]
@chrishenzie This is already a feature.

![Quit on "esc" option](https://i.imgur.com/Xzm9VPd.png)

**Comment by chrishenzie** [comment]
Wow `/facepalm`, I don't know how I missed this when it was right in front of me. Nevermind, thanks!
