### ISSUE TITLE
Conflict with TipTac - LFG Bulletin Board v3.23 overrides tooltip anchor

### ISSUE THREAD

**Issue by ESPI101** [Vysci/LFG-Bulletin-Board#220]
**Describe the bug**
If you have both of these addons installed:
- LFG Group Bulletin Board v3.23 
- TipTac Reborn (v24.03.23-release)

LFG will override the position of the tooltip anchor. If I roll back to v3.21 of LFG Bulletin Board, the issue isn't there.

**To Reproduce**
1. Install both addons listed above
2. Move the game tooltip anchor in TipTac
3. Notice the tooltip anchor is getting overriden by LFG Bulletin Board

**Comment by juemrami** [comment]
There hasn't been any changes to how the addon anchors tooltips related to the request list (Anchors to the bottom of the Bulletin Board frame) from 3.21 to now. 

Are you talking about how request tooltip (like many other tooltips) doesn't respect the TipTac anchor?

**Comment by juemrami** [comment]
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/20932280/e5f74ea5-9339-4f98-b9a7-96a95307fb8f)

**Comment by juemrami** [comment]
closing as stale. No follow up/reproduction.
