### ISSUE TITLE
STV and Loops tag

### ISSUE THREAD

**Issue by proVone** [Vysci/LFG-Bulletin-Board#222]
Hey, 

Could you add STV to bloodmoon and add loops to incursions for SoD please.

**Comment by juemrami** [comment]
Make sure your running on the latest version of the addon and in the options making sure that the checkboxes for "Incursion" and "Bloodmoon" are selected. 

Alternatively you can use the search feature to filter out request without the keywords typed (ie "loops"/"incursion"/"stv"/etc)
