### ISSUE TITLE
Lua error to do to `SUMMER` holiday event

### ISSUE THREAD

**Issue by juemrami** [Vysci/LFG-Bulletin-Board#253]
**Describe the bug**

Related Issues: 
  - https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=645
  - https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=647

```
3x LFGBulletinBoard/LibGPIOptions.lua:587: attempt to concatenate local 'TXTLeft' (a nil value)

[string "@LFGBulletinBoard/LibGPIOptions.lua"]:587: in function `AddEditBox'

[string "@LFGBulletinBoard/Options.lua"]:78: in function <LFGBulletinBoard/Options.lua:51>

[string "@LFGBulletinBoard/Options.lua"]:425: in function `OptionsInit'

[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:628: in function `Init'

[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:844: in function `?'

[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:117: in function <LFGBulletinBoard/LibGPIToolBox.lua:114>
```

**To Reproduce**
On Login

**Additional context**
Bug caused by recently added `"SUMMER"` entry for the latest holiday event to match the existing event infrastructure in the addon, However, a matching entry for `"SUMMER"` was not properly created in the `Tags.lua`. 

Its been disabled in `v3.315`  released on CF (not committed on this repo), ill push a more permanent fix to main with the release of `3.32`, not sure if people will even be looking for groups traditionally for the holiday events, im assuming you can queue into them now like random dungeon finder.

**Comment by Veznaren** [comment]
Message: Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:587: attempt to concatenate local 'TXTLeft' (a nil value)
Time: Fri Jun 21 02:47:11 2024
Count: 1
Stack: Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:587: attempt to concatenate local 'TXTLeft' (a nil value)
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua"]:587: in function `AddEditBox'
[string "@Interface/AddOns/LFGBulletinBoard/Options.lua"]:78: in function <Interface/AddOns/LFGBulletinBoard/Options.lua:51>
[string "@Interface/AddOns/LFGBulletinBoard/Options.lua"]:425: in function `OptionsInit'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:628: in function `Init'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:844: in function `?'
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua"]:117: in function <Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua:114>

Locals: DB = <table> {
 Heroic = ""
 SML = ""
 DM = ""
 AQ40 = ""
 SCH = ""
 RFC = ""
 MC = ""
 NAXX = ""
 RFK = ""
 SFK = ""
 AQ20 = ""
 BFD = ""
 WC = ""
 BWL = ""
 DMW = ""
 Search = ""
 LBRS = ""
 STK = ""
 MAR = ""
 ULD = ""
 DMN = ""
 STR = ""
 GNO = ""
 ST = ""
 SMA = ""
 SMG = ""
 ONY = ""
 Suffix = ""
 DME = ""
 SMC = ""
 Bad = ""
 ZG = ""
 UBRS = ""
 BRD = ""
 RFD = ""
 ZF = ""
}
Var = "SUMMER"
Init = ""
TXTLeft = nil
width = 445
widthLeft = 200
onlynumbers = false
tooltip = nil
suggestion = ""
c = 160
ButtonName = "LFGBulletinBoardO_Edit_160SUMMER"
CatName = "LFGBulletinBoardO_Edit_160SUMMER_Text"
(*temporary) = <function> defined =[C]:-1
(*temporary) = LFGBulletinBoardO_Edit_160SUMMER_Text {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = nil
(*temporary) = ""
(*temporary) = "OVERLAY"
(*temporary) = "GameFontNormal"
(*temporary) = "attempt to concatenate local 'TXTLeft' (a nil value)"
Options = <table> {
 AddEditBox = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:578
 __EditBoxLostFocus = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:562
 __EditBoxGetFocus = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:552
 _DoOk = <function> defined @Interface/AddOns/LFGBulletinBoard/Options.lua:267
 Prefix = "LFGBulletinBoardO_"
 AddText = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:485
 AddSpace = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:650
 Panel = <table> {
 }
 EditCheckBox = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:453
 _DoCancel = <function> defined @Interface/AddOns/LFGBulletinBoard/Options.lua:272
 __EditBoxOnEnterPressed = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:574
 Indent = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:170
 NextRelativ = "LFGBulletinBoardO_Edit_159ONY_Text"
 _DoDefault = <function> defined @Interface/AddOns/LFGBulletinBoard/Options.lua:283
 NextRelativY = -10
 EndInLine = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:180
 Index = <table> {
 }
 DoOk = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:32
 Color = <table> {
 }
 inLine = false
 EditText = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:517
 CurrentPanel = LFGBulletinBoardO_OptionFrame3ScrollChild {
 }
 NextRelativX = 0
 Vars = <table> {
 }
 AddDrop = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:401
 scale = 0.850000
 DoDefault = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:95
 Edit = <table> {
 }
 Btn = <table> {
 }
 EditCategory = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:214
 Frames = <table> {
 }
 __EditBoxTooltipShow = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:537
 InLine = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:175
 Init = <function> defined @Interface/AddOns/LFGBulletinBoard/LibGPIOptions.lua:11
 AddVers

**Comment by Veznaren** [comment]
Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:59: bad argument #1 to 'lower' (string expected, got nil)
Time: Fri Jun 21 02:51:26 2024
Count: 2
Stack: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:59: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:59: in function `Split'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:431: in function `CreateTagList'
[string "@Interface/AddOns/LFGBulletinBoard/Options.lua"]:136: in function `OptionsUpdate'
[string "@Interface/AddOns/LFGBulletinBoard/Options.lua"]:270: in function `OnCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:615: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:613>
[string "=[C]"]: in function `xpcall'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:591: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:588>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:599: in function `ForEachCanvas'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:613: in function `CommitCanvases'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:320: in function `Commit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:356: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:330: in function `Close'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:86: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:85>

Locals: (*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by juemrami** [comment]
thanks for providing the full output. Looking into this.
