### ISSUE TITLE
no group wants to appear

### ISSUE THREAD

**Issue by Obscurhaze** [Vysci/LFG-Bulletin-Board#267]
![Bug wow](https://github.com/Vysci/LFG-Bulletin-Board/assets/174988051/85b6bb79-2172-4e87-907c-96b3c75cddcb)

When people ask for LFG or LFM nothing appears in the lfg bulletins.

I deleted reinstalled, took a less recent version. I've done everything and it doesn't work.

I have the same config as my friend and for him everything works like new.

If anyone could help me so I can see people asking for help or something.

the only channel that I can see in the LFG BULLETIN window is travel.

**Comment by juemrami** [comment]
Hey, do you have any dungeon filters selected? (see image, ignore whacky colors)
![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/20932280/af00b34d-0def-46bc-8353-f8725014c5ca)

**Comment by Obscurhaze** [comment]
oh my god, thank you for your help I didn't notice that you could click on the (-) to scroll my menu.

thank you very much for your help :)

**Comment by juemrami** [comment]
Np. Glad i could help!
