### ISSUE TITLE
Full german part

### ISSUE THREAD

**Issue by Fyler74** [Vysci/LFG-Bulletin-Board#28]
Hello,

thanks for the great addon!

I've added the full German part and tested and optimized it over the past few days.
It works pretty well.
Should I see errors in the future, I will post an update.

Regards 
Fyler

[Tags.zip](https://github.com/Vysci/LFG-Bulletin-Board/files/6637871/Tags.zip)

**Comment by Vysci** [comment]
I pushed out German localization recently. Can you verify if the latest changes work correctly ? 

There has been 3-4 iterations of German localization that I’m hesitant for another iteration without confirming it is an actual problem in the latest code

**Comment by Vysci** [comment]
I have had a confirmation that german does work in v2.50. Closing the issue please reopen if there are still issues

**Comment by odog13** [comment]
flyer74 tags are better then the actual tags.lua you can download ... german here ... i posted curseforge as user veganmachtkrank then it leads me here after i read comments .. it works like a charm just sayin

**Comment by Fyler74** [comment]
The original tags are unfortunately very rudimentary and incomplete and only led to a few results.
The Germans use many abbreviations and have many names for some dungeons.
Typing errors are also common.
I took all of this into account in tests that lasted for days and included it in the tags.
I posted the tags here in the hope that German-speaking players can also benefit from the great add-on.
