### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [Vysci/LFG-Bulletin-Board#281]
**Describe the bug**
1x ...rfaceLFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:147: in function `FilterDungeon'
[string "@LFGBulletinBoard/RequestList.lua"]:867: in function `ParseMessage'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:845: in function `?'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:119: in function <LFGBulletinBoard/LibGPIToolBox.lua:116>

Locals:
dungeon = "DFC"
isHeroic = false
isRaid = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = false
 InitGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 32
 LfgRequestHideTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @LFGBulletinBoard/dungeons/classic.lua:273
 suffixTags = <table> {
 }
 LevelRange = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1752399386
 UpdateLfgToolNoSearch = <function> defined @LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:328
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:871
 WOTLKDUNGEONSTART = 33
 dungeonSecondTags = <table> {
 }
 rawClassicDungeonInfo = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @LFGBulletinBoard/CustomCategories.lua:148
 GetDungeons = <function> defined @LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 33
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @LFGBulletinBoard/RequestList.lua:1037
 OptionsInit = <function> defined @LFGBulletinBoard/Options.lua:280
 AllowInInstance = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:50
 MSGPREFIX = "LFG Bulletin Board: "
 UpdateLfgTool = <function> defined @LFGBulletinBoard/LfgToolList.lua:207
 OptionsUpdate = <function> defined @LFGBulletinBoard/Options.lua:113
 Announce = <function> defined @LFGBulletinBoard/Chat.lua:140
 LFG_UPDATETIME = 10
 LfgUpdateList = <function> defined @LFGBulletinBoard/LfgToolList.lua:489
 BtnSelectChannel = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:264
 GetCustomFilterNames = <function> defined @LFGBulletinBoard/CustomCategories.lua:198
 LfgRequestShowTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:678
 GetRaids = <function> defined @LFGBulletinBoard/Dungeons.lua:702
 L = <table> {
 }
 ElapsedSinceListUpdate = 0.080000
 Init = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:503
 ENDINGDUNGEONEND = 39
 SyncCustomFilterTags = <function> defined @LFGBulletinBoard/CustomCategories.lua:167
 RequestList = <table> {
 }
 ShouldReset = false
 LFG_Timer = 1720860707
 RaidList = <table> {
 }
 locales = <table> {
 }
 TBCDUNGE

**Desktop (please complete the following information):**
 - Version 3.34

**Comment by waytoomuchgaming** [comment]
Another one :
2x LFGBulletinBoard/RequestList.lua:807: attempt to perform arithmetic on field 'last' (a nil value)
[string "@LFGBulletinBoard/RequestList.lua"]:807: in function `ParseMessage'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:845: in function `?'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:119: in function <LFGBulletinBoard/LibGPIToolBox.lua:116>

Locals:
msg = "C#RE##any high level tailor on ?"
sender = "Meddl-ZandalarTribe"
guid = "Player-5232-0291C725"
channel = "topSekrtiChan"
appendTime = 0.940000
requestTime = 1720861100.940000
doUpdate = false
locClass = "Warlock"
engClass = "WARLOCK"
locRace = "Gnome"
engRace = "Gnome"
Gender = 2
gName = "Meddl"
gRealm = ""
name = "Meddl"
server = "ZandalarTribe"
updated = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
(for control) = 9
ir = 9
req = <table> {
 dungeon = "DFC"
 IsPastPlayer = false
 guid = "Player-5232-0291C725"
 start = 1720861001.464000
 class = "WARLOCK"
 IsFriend = false
 IsGuildMember = false
}
(*temporary) = nil
(*temporary) = 10
(*temporary) = "table"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'last' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = false
 InitGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 32
 LfgRequestHideTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @LFGBulletinBoard/dungeons/classic.lua:273
 suffixTags = <table> {
 }
 LevelRange = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1752399386
 UpdateLfgToolNoSearch = <function> defined @LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:328
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:871
 WOTLKDUNGEONSTART = 33
 dungeonSecondTags = <table> {
 }
 rawClassicDungeonInfo = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @LFGBulletinBoard/CustomCategories.lua:148
 GetDungeons = <function> defined @LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 33
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @LFGBulletinBoard/RequestList.lua:1037
 OptionsInit = <function> defined @LFGBulletinBoard/Options.lua:280
 AllowInInstance = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:50
 MSGPREFIX = "LFG Bulletin Board: "
 UpdateLfgTool = <function> defined @LFGBulletinBoard/LfgToolList.lua:207
 OptionsUpdate = <function> defined @

Both errors appened while doing nothing (OOC, not moving or interacting).

**Comment by waytoomuchgaming** [comment]
I think it conflict  with another addon (i have a lot of lua errors, not just the 2 i posted).
I disabled the search on the chanel the other addon set up, and it seems ok.

**Comment by Vysci** [comment]
@waytoomuchgaming what game version awere you playing

**Comment by Belden1** [comment]
![image](https://github.com/user-attachments/assets/281ce1b0-28f6-4a7d-aded-e09841b451a0)

![image](https://github.com/user-attachments/assets/21a9f2aa-97d9-4260-96a5-bbd66a679cf1)

Same problem, classic era (1.15.3.55563), v3.34

**Comment by Vysci** [comment]
@Belden1 @waytoomuchgaming I'll look closer at it in next day or two. Not a whole lot of sleep past couple days.

In the mean time you can run the following command in chat. `/run GroupBulletinBoard_Addon.DBChar["FilterDungeonDFC"] = false` you can just copy and paste in chat

**Comment by waytoomuchgaming** [comment]
> /run GroupBulletinBoard_Addon.DBChar["FilterDungeonDFC"] = false

The command don't do anything.
WoW is 1.15.3(55563).
But disabling a certain chanel (the one created by addon Greenwall) in LFG solve the problem. No more bug.

**Comment by juemrami** [comment]
@Vysci, Ive force enabled `FilterDungeonDFC` to `true` on my client, but im not able to reproduce @Belden1's issue. (im on 3.34)
![image](https://github.com/user-attachments/assets/17b58f34-e348-4c9a-91bf-ca7dbd75ddb3)


If you're experience the issue still after running `/run GroupBulletinBoard_Addon.DBChar["FilterDungeonDFC"] = false`, then it would help if you could copypaste the full text from BugGrabber @Belden1. Ty for reporting.

**Comment by juemrami** [comment]
Got the error on cataclysm
```
1599x ...rfaceLFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:147: in function `FilterDungeon'
[string "@LFGBulletinBoard/RequestList.lua"]:867: in function `ParseMessage'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:852: in function `?'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:119: in function <LFGBulletinBoard/LibGPIToolBox.lua:116>

Locals:
dungeon = "DFC"
isHeroic = false
isRaid = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = false
 InitGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 51
 LfgRequestHideTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @LFGBulletinBoard/dungeons/cata.lua:497
 suffixTags = <table> {
 }
 LevelRange = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1721081727.220000
 UpdateLfgToolNoSearch = <function> defined @LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:328
 ScrollGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:253
 OnLoad = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:878
 WOTLKDUNGEONSTART = 52
 dungeonSecondTags = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @LFGBulletinBoard/CustomCategories.lua:158
 GetDungeons = <function> defined @LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 28
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @LFGBulletinBoard/RequestList.lua:1037
 OptionsInit = <function> defined @LFGBulletinBoard/Options.lua:280
 AllowInInstance = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:50
 MSGPREFIX = "LFG Bulletin Board: "
 UpdateLfgTool = <function> defined @LFGBulletinBoard/LfgToolList.lua:207
 OptionsUpdate = <function> defined @LFGBulletinBoard/Options.lua:113
 Announce = <function> defined @LFGBulletinBoard/Chat.lua:140
 LFG_UPDATETIME = 10
 LfgUpdateList = <function> defined @LFGBulletinBoard/LfgToolList.lua:489
 BtnSelectChannel = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:264
 GetCustomFilterNames = <function> defined @LFGBulletinBoard/CustomCategories.lua:208
 LfgRequestShowTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:678
 GetRaids = <function> defined @LFGBulletinBoard/Dungeons.lua:702
 L = <table> {
 }
 ElapsedSinceListUpdate = 0.334000
 Init = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:503
 ENDINGDUNGEONEND = 110
 SyncCustomFilterTags = <function> defined @LFGBulletinBoard/CustomCategories.lua:177
 RequestList = <table> {
 }
 ShouldReset = false
 cataRawDungeonInfo = <table> {
 }
 RaidList =
 ```

**Comment by juemrami** [comment]
I found the source of the issue i think @Vysci. Whats the reason for including

`DFC` in this conditional block of `GBB.GetDungeons()`
```lua
if dungeons["DEADMINES"] 
  and not dungeons["DMW"] 
  and not dungeons["DME"] 
  and not dungeons["DME"] 
  and name ~= nil 
then
  if nameLevel>0 and nameLevel<40 then
    dungeons["DM"]=true
    dungeons["DM2"]=false
    dungeons["DFC"]=false
  else
    dungeons["DM"]=false
    dungeons["DM2"]=true
    dungeons["DFC"]=true
  end
end
```

From when i looked into the code last, these were added here a when the original author was trying to add his hacks so that messages with "dm" in it would get propperly identified as either for Dire Maul or Deadmines.
