### ISSUE TITLE
Sethekk Halls & Shattered Halls

### ISSUE THREAD

**Issue by miraage** [Vysci/LFG-Bulletin-Board#29]
Currently, Shattered Halls are shown when you type "sh", but it had never been this way.

sh = sethekk halls
shh = shattered halls

**Comment by Vysci** [comment]
Was basing the abbreviations based on https://wow.allakhazam.com/wiki/Instance_Abbreviation_List_%28WoW%29 and https://wowpedia.fandom.com/wiki/The_Burning_Crusade_instances_by_level which both say SH = Shattered Halls. Ill keep an eye out though on what typical abbreviations are using for these 2 in game

**Comment by Vysci** [comment]
Closing as no further comments and haven't seen any evidence of the said abbreviations. Can also modify this in the "search patterns" under settings
