### ISSUE TITLE
Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by johanpettersson1** [Vysci/LFG-Bulletin-Board#293]
Message: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)
Time: Sat Jul 20 18:44:26 2024
Count: 1
Stack: ...rface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:147: in function `FilterDungeon'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:867: in function `ParseMessage'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:845: in function `?'
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua"]:119: in function <Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua:116>

Locals: dungeon = "DFC"
isHeroic = false
isRaid = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @Interface/AddOns/LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = false
 InitGroupList = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 32
 LfgRequestHideTooltip = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @Interface/AddOns/LFGBulletinBoard/dungeons/classic.lua:273
 suffixTags = <table> {
 }
 LevelRange = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1721504053.909000
 UpdateLfgToolNoSearch = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @Interface/AddOns/LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:328
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:871
 WOTLKDUNGEONSTART = 33
 dungeonSecondTags = <table> {
 }
 rawClassicDungeonInfo = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @Interface/AddOns/LFGBulletinBoard/CustomCategories.lua:148
 GetDungeons = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @Interface/AddOns/LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 33
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @Interface/AddOns/LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:1037
 OptionsInit = <function> defined @Interface/AddOns/LFGBulletinBoard/Options.lua:280
 AllowInInstance = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:50
 MSGPREFIX = "LFG Bulletin Board: "
 UpdateLfgTool = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:207
 OptionsUpdate = <function> defined @Interface/AddOns/LFGBulletinBoard/Options.lua:113
 Announce = <function> defined @Interface/AddOns/LFGBulletinBoard/Chat.lua:140
 LFG_UPDATETIME = 10
 LfgUpdateList = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolLi

![image](https://github.com/user-attachments/assets/8cf6e8cc-db10-4d3c-8d87-05a4d9d49832)

**Comment by juemrami** [comment]
Deleting. Post on #294
