### ISSUE TITLE
WoW Cata - Bastion of Twilight Filter Broken

### ISSUE THREAD

**Issue by knobs-afk** [Vysci/LFG-Bulletin-Board#299]
**Describe the bug**
Messages with "bot" do not get filtered under the "Bastion of Twilight" group. Enabling "Botanica" filter will put messages with "bot" under that group. With "Botanica" disabled messages containing "bot" do not get filtered to any group.

**To Reproduce**
No special steps. Open LFG Bulletin Board and wait for a message containing "bot" to be posted and see whether it filters correctly.

**Expected behavior**
Messages with "bot" should get filtered to the "Bastion of Twilight" group when it is enabled. If "Botanica" is also enabled it should filter to both groups.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 3.36
 
**Additional context**
I believe it was filtering correctly a couple versions ago. Tried checking changelogs but didn't see any obvious fixes to the issue. A quick hacky solution was editing /dungeons/cata.lua line 147:
`BOT = 173,  -- The Botanica`
to 
`BOT3 = 173, -- The Botanica `
... now it will filter Bastion correctly but not Botanica.

**Comment by juemrami** [comment]
Disable the "The Botanica" filter from the filter settings
![image](https://github.com/user-attachments/assets/97716e7f-9129-447e-868f-c6f88ef05cef)

**Comment by knobs-afk** [comment]
I have Botanica disabled and Bastion of Twilight enabled. "Bot" does not get filtered to any group.
