### ISSUE TITLE
The Ring of Blood quest appears in dungeons (Russian)

### ISSUE THREAD

**Issue by Nikyou** [Vysci/LFG-Bulletin-Board#30]
1. I think it saw "пс" in "дпс" and filtered it as Wailing Caverns(Пещера Стенаний)
2. Every "арена" goes to Blackrock Depths. Maybe because it thinks that they are looking for BRD arena run.
![Nagrand](https://user-images.githubusercontent.com/26933913/121705521-61a94b00-cadd-11eb-9a36-1e9d0bd557aa.png)

**Comment by Vysci** [comment]
It's a slight issue but not much to be done here due to overlap of the word arena, and don't think it makes sense to remove it. Won't fix
