### ISSUE TITLE
WoW Classic Era V.1.15.3 - No longer working since latest update (08/27/2024)

### ISSUE THREAD

**Issue by maximus210793** [Vysci/LFG-Bulletin-Board#308]
Hi,
I am playing WoW Classic Era V 1.15.3, since the latest update 3.37 (08/27/2024) the addon is no longer loading ingame.
The last working version was 3.36 (07/24/2024).

A fix would be great.
Thanks in advance.

**Comment by juemrami** [comment]
thanks for the Report. 
Do you have any error output?
Does `/gbb` take you to the addon settings?

I may have to wait for more reports, or more info to debug this because i'm not able to replicate the behaviour.

**Comment by maximus210793** [comment]
1. Do you have any lua error output?
-> No, I do not get any LUA errors

2. Does /gbb take you to the addon settings?
-> yes, it worked.

I just noticed while doing step 2, that the minimap icon just disappeared after the update, now it is showing again.
Thanks for your help!

**Comment by juemrami** [comment]
Glad to hear it, yea i fixed a bug with the minimap and some of its default settings were changed. sorry about that.
