### ISSUE TITLE
Random chat going to the Misc tab.

### ISSUE THREAD

**Issue by Lurkee** [Vysci/LFG-Bulletin-Board#314]
**Describe the bug**
Pretty much the title, see screenshot.

**To Reproduce**
Not sure what's triggering this behavior.

**Expected behavior**
Pretty obvious, not to have chat messages posted for the world to see.

**Screenshots**
![Screenshot_20240912_142530](https://github.com/user-attachments/assets/1f395fa8-8d3f-4355-8818-68c7b2e97905)

**Desktop (please complete the following information):**
 - Version [e.g. v2.48]

**Additional context**

**Comment by juemrami** [comment]
The misc category pretty much collects any thing that has the LFG or associated keywords for a typical looking for group message, which includes things like class names or the phrase "lfg"

See [`searchTags in Tags.lua for the full list`](https://github.com/Vysci/LFG-Bulletin-Board/blob/main/LFGBulletinBoard/Tags.lua#L41) here
