### ISSUE TITLE
Addon doesn't work in SoD BWL/ZG patch

### ISSUE THREAD

**Issue by adam-tj** [Vysci/LFG-Bulletin-Board#315]
**Describe the bug**
It doesn't work. The minimap button is not there. "/gbb" is completely empty. "/gbb config" is also empty and doesn't work.

**To Reproduce**
1a. Look at minimap
2a. See no minimap button

1b. "/gbb"
2b. See it is empty

1c. "/gbb config"
2c. See it is empty

**Expected behavior**
To see the minimap button. To see the list of people looking for groups. To see the settings.

**Screenshots**
![image](https://github.com/user-attachments/assets/46c2432f-1398-4da0-afc1-8980110d390b)
Minimap, default window, and settings window are visibly empty and/or not present while I am in LFG chat as seen in the bottom left chat.

**Desktop (please complete the following information):**
 - LFGBulletinBoard-v3.38-classic.zip

**Additional context**
Classic SoD, BWL/ZG patch. The screenshot might be a little deceiving because I am making the game look a little bit like Dragonflight.

**Comment by adam-tj** [comment]
For whatever reason it works now, some other addon might have caused it to break.

**Comment by Vysci** [comment]
Glad to hear it because I couldn't repro it
