### ISSUE TITLE
Include your Current level and Class in the Alt-click response.

### ISSUE THREAD

**Issue by Raidein1** [Vysci/LFG-Bulletin-Board#324]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the alt-click function and response to include something like [Current Level] [Current Class] will [role] for [%s].

**Describe the solution you'd like**
I have below what I currently use but would like to be able to add an dynamic level and class to the format string.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/71c74303-458e-474d-a3d6-9c94767aef3e)

**Comment by juemrami** [comment]
Okay i understand what you were saying on curseforge now.

related issue:
 - #38

**Comment by juemrami** [comment]
fwiw i have thought about this feature, and the general ability to customize these messages further. 

Ill take a look at implementing something as a hotfix for you.

**Comment by Vysci** [comment]
I’m thought this was added previously. At least looks like at least attempted https://github.com/Vysci/LFG-Bulletin-Board/pull/86

**Comment by juemrami** [comment]
@Raidein1 in #325 ive added some new text replacements, `%level`, `%class`, `%role` `%dungeon`

**example img**
![WowClassic_fea8YN1fH8](https://github.com/user-attachments/assets/aa10ebc5-7b61-4521-8f9c-8f2dbaeeba60)
![WowClassic_SXTzzmA1Cf](https://github.com/user-attachments/assets/742e3b17-8980-4630-900d-d746ea2407a1)

**Comment by juemrami** [comment]
@Raidein1, You can test it out on v3.41-beta. Im planning to make the settings ui for this better, probably like with #86.

cf link: https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/files/5934900

**Comment by Raidein1** [comment]
@juemrami I installed the beta version but for me alt click doesn't produce anything. I can shift click to get the /who and ctrl click to invite but the message from alt click is not working for me. Please see screenshot below for my localization is set to default settings.
![image](https://github.com/user-attachments/assets/f686aa42-afaf-490c-8aeb-b3b2605690cb)

**Comment by juemrami** [comment]
Okay, ive check it out, i know whats causing the issue. 
Mind trying out a custom string?

**Comment by juemrami** [comment]
> will push a new beta release soon.

https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/files/5937237

**Comment by Raidein1** [comment]
[image: image.png]
Worked like a champ.

**Comment by juemrami** [comment]
Alright ive added some new settings elements for editing this message in #327
![image](https://github.com/user-attachments/assets/f999e0e7-7144-410c-aee0-06000eeb4510)
I mentioned this in the PR, but that message that we've been changing in the `Localization` settings panel is now just the default/fallback message

Users are now meant to use this new input box in the main addon settings panel

@Raidein1, Your saved message should persist when the official release version is out, but letting you know as a heads up incase you find that the message has magically reset back to the original addon's default.

(link if you dont have curseforge set to download beta versions)
**v3.41-beta3**: https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/files/5942690
