### ISSUE TITLE
Remove Guild Ranks from tooltips

### ISSUE THREAD

**Issue by SilverSaw** [Vysci/LFG-Bulletin-Board#329]
Please add an additional checkbox to remove Gild Ranks from the tooltips when "Add guild in player tooltip" is turned on.

I always have to remove them manually:
				self:AddLine(GBB.Tool.RGBtoEscape(GBB.DB.ColorGuild).."<"..guildName..">")

**Comment by juemrami** [comment]
Sure.
This is a legacy option anyways. Im wondering how many users actually even have it enabled?
I want to eventually cull some of the more random options.

Ideally the addon would only add to the tooltips generated from the bulletin board itself, as i personally find it annoying when addons add stuff to the base game tooltip

**Comment by SilverSaw** [comment]
Thanks for the response @juemrami and thanks for this great addon!

**Comment by juemrami** [comment]
This will be included as part of ` v3.41`, check out the latest beta build on curseforge to try it out

**Comment by SilverSaw** [comment]
@juemrami working like a charm, thanks!
