### ISSUE TITLE
Add Guild Rank Text back in

### ISSUE THREAD

**Issue by Fearture1459** [Vysci/LFG-Bulletin-Board#333]
According to update 3.41, Guild rank text was removed from the "Add guild in player tooltip" setting.

This tooltip change was something I was happily using since TinyTooltip doesn't function properly in SoD, and GuildTooltip also tosses too many LUA errors to be considered. Please consider re-adding it back in. It is helpful for identifying Officer rank players in guilds in case I have questions about their guild or players in their guild, without having to /who and ask every person in their guild who might be an officer that's online.

![image](https://github.com/user-attachments/assets/c400b061-7c50-4a4e-8ad0-9f944d840504)

**Comment by E4io555** [comment]
Yes, please add this back.

**Comment by juemrami** [comment]
Thanks for the feedback will add this back in promptly
