### ISSUE TITLE
Extend announcement feature

### ISSUE THREAD

**Issue by mikkel-ol** [Vysci/LFG-Bulletin-Board#34]
Announcement feature per dungeon, perhaps with keyword support. 

Example: announcement on requests with "mage" keyword in dungeons "Black Morass" and "Steamvault".

**Comment by Vysci** [comment]
There is an announcement feature per dungeon. 

It can be configured via settings
<img width="482" alt="Screen Shot 2021-06-11 at 11 06 42 AM" src="https://user-images.githubusercontent.com/84870873/121730921-24c16200-caa5-11eb-9624-59d1c7809d87.png">

or by right clicking on the board 
<img width="714" alt="Screen Shot 2021-06-11 at 11 02 05 AM" src="https://user-images.githubusercontent.com/84870873/121731182-71a53880-caa5-11eb-9875-afa0ad9daf5b.png">

As far as the mage keyword thing, once fix the bug on the custom patterns, you can add mage to the "search words" under search patterns settings

reopen if this isn't what you meant

**Comment by mikkel-ol** [comment]
What I'm missing atm is, when I'm looking for groups for, say, Steamvault and Shattered Halls for instance, I would like an announcement for new requests for those two dungeons, **but not for all messages**. Instead, I would like announcement whenever the keyword "dps" and/or "mage" or whatever is in the message.

Does that make more sense?
