### ISSUE TITLE
Classic dungeon level ranges

### ISSUE THREAD

**Issue by aribrown913** [Vysci/LFG-Bulletin-Board#36]
Your dungeon level ranges are incorrect for the 1-60 dungeons in your TBCC version. Patch 2.3 modified the mob level ranges in many instances to be smaller and in a lot of cases, lower level. Here are the updated level ranges:

Ragefire Chasm 13-16

Wailing Caverns 17-21

Shadowfang Keep 18-21 (very different from Classic)

The Deadmines 18-22

Blackfathom Deeps 22-24 (another very different one)

The Stockade 23-29

Razorfen Kraul 24-27 (hugely lower range)

Gnomeregan 25-28 (hugely lower range)

SM Graveyard 30-32

SM Library 33-35

Razorfen Downs 34-37 (hugely lower range)

SM Armory 35-37

SM Cathedral 36-40

Uldaman 36-40 (hugely lower range)

Zul'Farrak 42-46

Maraudon 43-48 (very different)

Temple of Atal'Hakkar 47-50 (very different)

Blackrock Depths 48-56

Blackrock Spire 54-60

Dire Maul 55-60

Scholomance 58-60

Stratholme 58-60

 

Note that these ranges are based on mob levels. You may wish to make them a little wider for the sake of the addon. A list of the level requirements to be summoned for a Meeting Stone in TBC can be found on the Wowpedia Meeting Stone page. But some of these definitely need adjusting so that people do not mistakenly think they are too low for a dungeon when they actually aren't.

 

Overall though I would consider this a well made and absolutely essential addon, especially until Blizzard gets their act together and gives us at least the basic manual LFG tool that was introduced in 2.0.1. The Burning Crusade expansion was designed with that tool in mind, not chat spamming.

 

Edit: After looking through the actual code of the addon, it appears you are aware of this and added separately defined ranges under GBB.PostTbcDungeonLevels in Dungeons.lua - but those values do not seem to actually be making it into the game, at least not in the interface.

 

Second edit: After changing the level ranges in GBB.VanillaDungeonLevels (Dungeons.lua), the level ranges shown in game have been modified as well. So I believe your TBCC addon is using those values by mistake.

**Comment by Vysci** [comment]
As you mentioned the dungeon ranges are kind of scuffed for those curious, it happens because a variable is being accessed before it's initialized so it results in using the incorrect ranges.

The dungeon ranges that are supposed to be displaying are based on the levels needed to access the summoning stone and not the mob level range
