### ISSUE TITLE
Click to send message

### ISSUE THREAD

**Issue by standaloneghost** [Vysci/LFG-Bulletin-Board#38]
Let me configure a message to send people so i can just click and send a message to whoever is lfg / LFM. "70 frost mage with table, inv", then click and send that to whoever is LFM the dungeon i want

**Comment by juemrami** [comment]
Also requested on CF
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=657

**Comment by juemrami** [comment]
closed with #324
