### ISSUE TITLE
"BM" is being tagged as Hellfire Citidel: Ramparts

### ISSUE THREAD

**Issue by cdurth** [Vysci/LFG-Bulletin-Board#47]
default filter it is tagging messages with BM as ramps.
Added "BM" to search pattern for The Black Morass and it produces the same result.

**Comment by cdurth** [comment]
default filter it is tagging messages with BM as ramps.
Added "BM" to search pattern for The Black Morass and it produces the same result.

**Comment by cdurth** [comment]
also dumping some entries into Black Temple.
potentially related to #32 ?

**Comment by Vysci** [comment]
Make sure that in search patterns under settings you turn off other languages

**Comment by cdurth** [comment]
> 
> 
> Make sure that in search patterns under settings you turn off other languages

ah that makes sense, and fixed it.
