### ISSUE TITLE
Heroic Filter Not Displaying Anything

### ISSUE THREAD

**Issue by itsthenewdc** [Vysci/LFG-Bulletin-Board#53]
Latest update 2.52 is not displaying anything when Heroic Only Filter is checked. When unchecked, "Normal" dungeons appear, but I can see in multiple postings that the word "Heroic" is being used in channels.

![image](https://user-images.githubusercontent.com/51030387/121968982-58b8b380-cd41-11eb-86de-b9ed20438e66.png)

![image](https://user-images.githubusercontent.com/51030387/121969012-679f6600-cd41-11eb-8893-ea7e98582f38.png)

**Comment by Macaddict42** [comment]
Can confirm, getting the same behavior

**Comment by Vysci** [comment]
This is due to "custom" being selected in search patterns, if you uncheck it in 2.52 it will fix the issue. 2.53 contains the fix

**Comment by Macaddict42** [comment]
Working now, thanks
