### ISSUE TITLE
Can't save filters

### ISSUE THREAD

**Issue by geoeki** [Vysci/LFG-Bulletin-Board#57]
Title basically says it all: no matter what I select or deselect in the filter menu, nothing of it is saved. Once I click ok with my set filters and reopen the Bulleting Board Menu, all is set back to "All selected". Using the latest version of the addon from Curseforge. No issues with other addons not saving the settings.

**Comment by Joxethings** [comment]
> Title basically says it all: no matter what I select or deselect in the filter menu, nothing of it is saved. Once I click ok with my set filters and reopen the Bulleting Board Menu, all is set back to "All selected". Using the latest version of the addon from Curseforge. No issues with other addons not saving the settings.

Having the same issue.

**Comment by Vysci** [comment]
Is this still an issue in v2.54? If it is mind providing some screen shots of filter page, search patterns, and general settings (click "LFG Bulletin Board" right above "Filter" in settings)

**Comment by Macaddict42** [comment]
I checked only custom search patterns. When I try to set heroic to anything and hit ok, the next time I open options, my settings are gone.

**Comment by Vysci** [comment]
Does this occur if you uncheck custom and check English? 

Can you turn on lua errors by typing “/console scriptErrors 1” and see if there are any errors when this issue occurs ? 

If no errors get displayed can you try turning off all add ins except bulletin board and see if it still occurs ? 

You can type “ /console scriptErrors 0” to hide errors again

**Comment by Macaddict42** [comment]
I figured out I can set the heroic search pattern, but I'm unable to set it to the same value as the example gray text. For example, I can set it to "heroic h hc", but not "h hc heroic". This behavior would be fine if it used the example text whe nothing is entered, but that's not the case.

**Comment by christiangruber** [comment]
Hi, the add-on still works, but I can't change any settings … it's always resetting to the previous settings. The add-on is updated, and I use it from WoWup in WoW SOD.

**Comment by juemrami** [comment]
This and similar issues would possibly fixed by feature request #200
