### ISSUE TITLE
Inaccurate LFG channel name for TBCC in french

### ISSUE THREAD

**Issue by Hantunaar** [Vysci/LFG-Bulletin-Board#65]
Hey there, I'm french and since I downloaded the addon I noticied I kept joining a channel named RechercheGroupe, which is basically LookingForGroup.

The thing is, while it was the accurate name for the channel in french during Classic vanilla, it was renamed with Burning Crusade to RechercheDeGroupe. So I keep joining this dead channel and it takes the /1 slot, making General becoming /2, Trade is now /3 etc... quite annoying!

I tried to change it in the localization settings, but after /reload the addon breaks and doesn't load at all.

**Comment by Vysci** [comment]
This should be fixed in the latest version 2.54
