### ISSUE TITLE
Dungeon specific Heroic filtering

### ISSUE THREAD

**Issue by azeda** [Vysci/LFG-Bulletin-Board#67]
**Is your feature request related to a problem? Please describe.**
I am still farming normal dungeons for specific BiS pieces, and to make it easier to find groups, I only display the dungeons I need those pieces from. The problem I am having is I also run Heroic dungeons in between, but I can't see groups for that unless I enable all dungeons and have a very cluttered window causing me to overlook groups.

**Describe the solution you'd like**
I would like the ability to for example: Enable the Mechanar dungeon for Normal OR Heroic and then be able to see the rest of the dungeons on Heroic only. 

**Describe alternatives you've considered**
Currently I just enable the daily and have to sift for Heroic when it comes up. 

**Additional context**
I realize the implementation of such a solution might require the checking of many boxes and possibly cluttering the UI. But if it can be implemented in a clean way I'd be so happy.

**Comment by chy8803** [comment]
Agree!

**Comment by Advice-Dog** [comment]
I created a PR that I believe addresses this issue, #105. If you enable 'filter by level', it'll now show level 68-70 normals, and heroics.

**Comment by azeda** [comment]
> 
> 
> I created a PR that I believe addresses this issue, #105. If you enable 'filter by level', it'll now show level 68-70 normals, and heroics.

I don't believe so. Lets say I'm Revered with Thrallamar, but that is my only Revered Faction so I -ONLY- want to see Heroic options for Ramparts, Blood Furnace and Shattered Halls, but see Normals for things like Steamvaults, I currently have no way to do this, it's all or nothing.
