### ISSUE TITLE
Use gray default custom search patterns if no value is entered in field

### ISSUE THREAD

**Issue by Macaddict42** [Vysci/LFG-Bulletin-Board#70]
Right now, if you only have custom search patterns checked, you have to enter a value into every single box. It would be great if it used the example search pattern if you don't override it with anything. It is weird because if you enter the exact text that the example shows, it will not save and gets reset when you click okay.

**Comment by Macaddict42** [comment]
Actually, it appears that the Search words box just doesn't work at all right now. I can enter anything I want into the box and I still get results that don't include that pattern.

**Comment by Macaddict42** [comment]
![image](https://user-images.githubusercontent.com/38168730/122318344-bda41300-ced3-11eb-9f88-c7957b1c1401.png)
![image](https://user-images.githubusercontent.com/38168730/122318396-d280a680-ced3-11eb-9a3e-9a98b74b6463.png)
![image](https://user-images.githubusercontent.com/38168730/122318479-f512bf80-ced3-11eb-8973-653c7fdfa131.png)

**Comment by Vysci** [comment]
It basically works like this: 

1. English (or w.e language) + custom selected: this will result in using all of the languages default values **AND** anything that has been entered manually
2. Only custom selected: it will **override** with the values have been entered. If fields were left blank then the value is blank
3. Only 1 language selected: it will use the languages default values and ignore anything that has been entered

You are right about search words though

**Comment by Macaddict42** [comment]
Why I'm looking for is a way to trigger only on a specific set of search words, not additional. For example, instead of triggering on "lfm lf1m lf2m lf3m", i want it to only trigger on "dps". This way, it will only show me groups that are looking for dps and exclude those who need a tank or healer. I also don't want it to interfere with filtering of heroic groups, so the separate search filter for heroic still needs to work as it currently does. Is that possible?

As it is now, if I check English + Custom, it will still trigger on "lfm lf1m lf2m lf3m etc." from English. However, if I only check Custom, then I have the issue of having to enter something for every single dungeon's search pattern. This is why I was hoping custom would use the default search pattern if you hadn't entered anything. That way it could work like a hybrid of English + Custom.

**Comment by juemrami** [comment]
Closing as stale, this type of problem should have been alleviated with #250, and #205
