### ISSUE TITLE
Minimap Button position does not properly save

### ISSUE THREAD

**Issue by Rewyn** [Vysci/LFG-Bulletin-Board#71]
Should be fairly self-explanatory.
Minimap button does not save its position on reload, even with the option to lock its position enabled.
When you tick/untick that option (after a restart/reload, so its on its default position) it'll actually jump to the intended position, so it does seem to _somehow_ save it.

I am using the sexymap addon with a square map if that matters. With the "Minimize minimap button distance" option ticked it properly moves in a square around it as well.

**Comment by Vysci** [comment]
Just FYI I have heard of multiple people mentioning this add on not working properly with sexymap addon

**Comment by Rewyn** [comment]
Huh. As long as that's the only issue with it (and I guess sexymap not being able to hide the minimap button), I'll live.
But I'll try without that and see if it persists.

**Comment by Vysci** [comment]
I will take a look but atm it’s low of my priority

**Comment by Rewyn** [comment]
Yeah, seems to work fine when I disable sexymap and reload. It's at worst a slight inconvenience, so pretty much whatever.

**Comment by Vysci** [comment]
Closing due to the nature of the bug (it's interaction with sexymap addon) and the low impact compared to time investment
