### ISSUE TITLE
Greyed, non functioning, "ghost" LookingForGroup channel

### ISSUE THREAD

**Issue by Hantunaar** [Vysci/LFG-Bulletin-Board#76]
While using the french client, the addon makes me join a LookingForGroup channel that takes the /1 slot. Every other channels are then shifted (General is now /2, Trade becomes /3 etc...)

Also this new channel is greyed in the chat settings and not useable: typing /1+space doesn't do anything.
I can't tick it neither.
If I delete it, it comes back immediately as /5 which at least brings back the right order to the other channels. 

Beside that the addon works just fine and get the LFG spam right.

![Greyed LFG](https://user-images.githubusercontent.com/56095922/122630412-1eac2200-d05f-11eb-877c-3532f01def4c.png)

**Comment by Vysci** [comment]
What version of the addon are you running?

As a short term fix go to "Settings" -> "Localization" scroll down until you see "lfg_channel". It most likely has the value of "LookingForGroup" change it to whatever the german lfg channel is and then do a /reload

**Comment by Hantunaar** [comment]
I'm using the latest one 2.55. Changing the value in the Localization settings doesn't seem to have any effect.

Actually, changing any value in the Localization settings doesn't have any effect despite /reload. The new text stays white but is not used by the addon.

**Comment by Vysci** [comment]
Thanks for bringing this to my attention, this is only an issue on non English clients hence why I didn’t catch this before. 

While I work on a fix I suggest moving the channel to be the last one on the list (so you can just ignore it exists). You can move it just  by clicking and dragging channel name in the WoW chat settings you posted

**Comment by Weryxx** [comment]
Temp fix for this is: Go into the Addon Folder "X:\World of Warcraft\_classic_\Interface\AddOns\LFGBulletinBoard"->Localization ->
"GBB.locales = {
	enGB = {
		["lfg_channel"]="LookingForGroup", -- must be the default chat-name!" 
		
and change the "LookingForGroup" part to your loca equivalent.

e.g. for german:
"GBB.locales = {
	enGB = {
		["lfg_channel"]="SucheNachGruppe", -- must be the default chat-name!" 

Working for me.

**Comment by Hantunaar** [comment]
Working for me too, thanks!
