### ISSUE TITLE
"WTB Primal Mana" showing as Mana Tombs HC

### ISSUE THREAD

**Issue by rasmuszimmer** [Vysci/LFG-Bulletin-Board#77]
![image](https://user-images.githubusercontent.com/5746348/122652575-d284de80-d13f-11eb-9f75-923bfd00ad16.png)

**Comment by Vysci** [comment]
Closing this as it’s kind of expected. The reality is there are going to be keywords it will incorrectly match. The alternative is either spend a bunch of time making matching better or make it more specific but at the cost of missing potential matches.
