### ISSUE TITLE
Minimap button gone

### ISSUE THREAD

**Issue by Fremferden** [Vysci/LFG-Bulletin-Board#78]
my mini map button is gone after a right click, have tried installing the addon again but without any luck, really enjoy this addon but now I can’t use it. Can you help ?

**Comment by Vysci** [comment]
Go to settings -> "LFG Bulletin Board" -> check "Minimize minimap button distance"

**Comment by blacksmith93** [comment]
Hi, trying any kind of combination of settings, then reloading and everything does not work to fix this bug. only way to access this addon for me is with /gbb

**Comment by rekcut12** [comment]
I am having this same problem. Has anyone been able to find a solution to this?
