### ISSUE TITLE
Filtering specific dungeons does not work properly

### ISSUE THREAD

**Issue by lbzg** [Vysci/LFG-Bulletin-Board#82]
**Describe the bug**
Checking specific dungeons in dungeon filter does not filter specific dungeons but shows all dungeons.
Seems like only "Filter on recommended level ranges" / "hc only" / "normal only" types of filter work.

**To Reproduce**
1. Go to filter settings
2. Click on unselect all
3. Select only few dungeons
4. All dungeons are shown in LFG Bulletin board instead of only checked ones

**Expected behavior**
Only dungeons that are checked should show in LFG Bulletin board

**Screenshots**
https://prnt.sc/168o9wl

**Desktop (please complete the following information):**
version: LFGBulletinBoard_v_2_55.zip

**Comment by Vysci** [comment]
Uncheck "Don't filter own request"
