### ISSUE TITLE
Normal, Heroic, Outland, Azeroth, Favorite options

### ISSUE THREAD

**Issue by Tenies** [Vysci/LFG-Bulletin-Board#87]
It would be nice to have some tik options at the top of the LFG window that for example i can select to show me only heroics or only Outland dungeons or only normal etc. I'm looking for heroics and i have to scroll all the time but also i dont want to permantly hide from the options normal and Azeroth dungeons. Multiple choices would be great!
Also a nice option would be to have favorites. Bookmark a dungeon with the option normal or/and heroic and then as i said above, give us an option to select favorites only. So for example i can tik my favorites (that includes some 2-3 normals) and also tik heroics so i can only see that i want and not a full list of useless, for me, dungeons.

**Comment by Vysci** [comment]
There already is filters for normal, heroic and raid (normal + heroic filter combined). You can also select the dungeons you want via filters (classic + tbc dungeons). 

You just click the setting button in bulletin board or right click in the bulletin board -> click filter, additionally you can right click minimap icon -> click filter

Bookmarking dungeons is a bit of a niche case. The effort to support bookmarks isn’t trivial and I just don’t have the time. If there is a larger demand for it I will reevaluate
