### ISSUE TITLE
Compatibility with boost spam addons? Or block it in LFGB?

### ISSUE THREAD

**Issue by azeda** [Vysci/LFG-Bulletin-Board#92]
**Is your feature request related to a problem? Please describe.**
I'm not certain if this is possible, but I have an add on that blocks boost spam from my chat. I realize that your add on is just scraping chat, but is it possible to only display what the boost spam add ons are allowing? Or can we block boost spam all together in LFGB?

**Describe the solution you'd like**
Block boost spam from LFGB, or give us the ability to set exclusion filters to block it ourselves.

**Describe alternatives you've considered**
I have an add on to block boost spam, but LFGB is ignoring what it blocks.

**Additional context**
Fuck boost spammers :)

**Comment by Vysci** [comment]
Settings -> Search patterns -> blacklist -> Add “wts” “boost” -> make sure custom is checked (along side with your language)
