### ISSUE TITLE
Filters not always applying.

### ISSUE THREAD

**Issue by azeda** [Vysci/LFG-Bulletin-Board#94]
**Describe the bug**
Filters are not always applying. For example I have 4 dungeons selected as well as Heroic only filtering turned on, and on some occasions, I'm getting different filtering displayed. 

**To Reproduce**
I am not 100% certain how to reproduce. My best GUESS is this happens if you play alts. I have noticed this typically happens after I log over from my 64 alt.

**Expected behavior**
Filters to display as I have selected them.

**Screenshots**
https://imgur.com/a/eUICpns

**Desktop (please complete the following information):**
 - Version 2.51

**Comment by Vysci** [comment]
Turn off "Don't filter own request"
