### ISSUE TITLE
Dungeon incorrectly categorized

### ISSUE THREAD

**Issue by danslo** [Vysci/LFG-Bulletin-Board#95]
![Screenshot-20210625221156-747x219](https://user-images.githubusercontent.com/743661/123480283-6bb16a80-d602-11eb-830c-eddc9bffcc97.png)

BM aka Black Morass is considered as Ramparts.

Version 2.5.7 (updated via WowUp).

**Comment by Vysci** [comment]
Go to Settings -> Search patterns -> Turn off German and other languages you aren't using

**Comment by danslo** [comment]
Thanks, and that would fix my problem...

I assume the majority of installs for this addon are english users. Wouldn't it make sense to default these settings to be off?

**Comment by Vysci** [comment]
As of few versions ago it only turns on the language that your client is using, however this isn’t reflected on users who had the add on before the change (their preferences are already saved which by default used to be every language)
