### ISSUE TITLE
Checkbox to make dungeons minimized by default.

### ISSUE THREAD

**Issue by Soothx** [Vysci/LFG-Bulletin-Board#98]
**Is your feature request related to a problem? Please describe.**
I am generally looking for 1 particular dungeon, but don't want to go into settings and constantly change around which one I'm looking for. So having to minimize all the dungeons I don't want to see, would be nice to avoid.

**Describe the solution you'd like**
A simple checkbox in the settings like:
"Minimize all dungeons by default"

**Describe alternatives you've considered**
Minimizing the dungeons myself manually every time, or disabling all dungeons and only enabling the one I want to see. In general, it's just a very minor quality of life thing, and honestly not that important.

**Additional context**
![image](https://user-images.githubusercontent.com/33608256/123523909-45a1ce00-d6c7-11eb-8396-cb5f7bd4ba19.png)

**Comment by Vysci** [comment]
Right click on a dungeon name -> Click Fold All. This will minimize all dungeons but yes you have to click it again every time you login

**Comment by Soothx** [comment]
Appreciate it, I must have overlooked it. Great addon ❤️
