### ISSUE TITLE
Changing font

### ISSUE THREAD

**Issue by drlkf** [Vysci/LFG-Bulletin-Board#99]
Hi,

I would like to change the font of my Bulletin window, do I have to edit the source code somewhere ? I tried searching the XML files and research on the web but the documentation is very sparse and I couldn't fond anything that would lead me to something useful.

Thanks !

**Comment by kanbaric** [comment]
This was annoyingly difficult to figure out, but I managed to lower the font size by replacing all uses of GameFontNormal and GameFontNormalLarge to GameFontNormalSmall.  Changed it in GroupBulletinBoard.xml and GroupList.lua, ignoring LibGPIOptions because thats just the options UI config.
